module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jest: true,
    node: true,
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
  },
  plugins: ['react', 'react-hooks', 'jsx-a11y', 'import', 'prettier', 'simple-import-sort'],
  rules: {
    'react/no-unescaped-entities': ['off'],
    'max-len': ['off'],
    'no-var': ['error'],
    'prettier/prettier': [
      'error',
      {
        arrowParens: 'avoid',
        jsxSingleQuote: true,
        printWidth: 120,
        singleQuote: true,
        trailingComma: 'all',
      },
      {
        usePrettierrc: false,
      },
    ],
    'simple-import-sort/exports': ['error'],
    'simple-import-sort/imports': ['error'],
    'arrow-body-style': ['off'],
    'prefer-arrow-callback': ['off'],
    curly: [0],
    'lines-around-comment': [0],
    'no-confusing-arrow': [0],
    'no-mixed-operators': [
      0,
      {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      },
    ],
    'no-tabs': [0],
    'no-unexpected-multiline': [0],
    quotes: [0],
    '@typescript-eslint/lines-around-comment': [0],
    '@typescript-eslint/quotes': [0],
    'array-bracket-newline': ['off'],
    'array-bracket-spacing': ['off'],
    'array-element-newline': ['off'],
    'arrow-parens': ['off'],
    'arrow-spacing': ['off'],
    'block-spacing': ['off'],
    'brace-style': ['off'],
    'comma-dangle': ['off'],
    'comma-spacing': ['off'],
    'comma-style': ['off'],
    'computed-property-spacing': ['off'],
    'dot-location': ['off', 'property'],
    'eol-last': ['off'],
    'func-call-spacing': ['off'],
    'function-call-argument-newline': ['off'],
    'function-paren-newline': ['off'],
    'generator-star-spacing': ['off'],
    'implicit-arrow-linebreak': ['off'],
    indent: ['off'],
    'jsx-quotes': ['off'],
    'key-spacing': ['off'],
    'keyword-spacing': ['off'],
    'linebreak-style': ['off'],
    'max-statements-per-line': ['off'],
    'multiline-ternary': ['off'],
    'newline-per-chained-call': ['off'],
    'new-parens': ['off'],
    'no-extra-parens': ['off'],
    'no-extra-semi': ['off'],
    'no-floating-decimal': ['off'],
    'no-mixed-spaces-and-tabs': ['off'],
    'no-multi-spaces': ['off'],
    'no-multiple-empty-lines': ['off'],
    'no-trailing-spaces': ['off'],
    'no-whitespace-before-property': ['off'],
    'nonblock-statement-body-position': ['off'],
    'object-curly-newline': ['off'],
    'object-curly-spacing': ['off'],
    'object-property-newline': ['off'],
    'one-var-declaration-per-line': ['off'],
    'operator-linebreak': ['off'],
    'padded-blocks': ['off'],
    'quote-props': ['off'],
    'rest-spread-spacing': ['off', 'never'],
    semi: ['off'],
    'semi-spacing': ['off'],
    'semi-style': ['off'],
    'space-before-blocks': ['off'],
    'space-before-function-paren': ['off'],
    'space-in-parens': ['off'],
    'space-infix-ops': ['off'],
    'space-unary-ops': ['off'],
    'switch-colon-spacing': ['off'],
    'template-curly-spacing': ['off'],
    'template-tag-spacing': ['off'],
    'unicode-bom': ['off', 'never'],
    'wrap-iife': ['off'],
    'wrap-regex': ['off'],
    'yield-star-spacing': ['off'],
    '@typescript-eslint/block-spacing': ['off'],
    '@typescript-eslint/brace-style': ['off'],
    '@typescript-eslint/comma-dangle': ['off'],
    '@typescript-eslint/comma-spacing': ['off'],
    '@typescript-eslint/func-call-spacing': ['off'],
    '@typescript-eslint/indent': ['off'],
    '@typescript-eslint/key-spacing': ['off'],
    '@typescript-eslint/keyword-spacing': ['off'],
    '@typescript-eslint/member-delimiter-style': ['off'],
    '@typescript-eslint/no-extra-parens': ['off'],
    '@typescript-eslint/no-extra-semi': ['off'],
    '@typescript-eslint/object-curly-spacing': ['off'],
    '@typescript-eslint/semi': ['off'],
    '@typescript-eslint/space-before-blocks': ['off'],
    '@typescript-eslint/space-before-function-paren': ['off'],
    '@typescript-eslint/space-infix-ops': ['off'],
    '@typescript-eslint/type-annotation-spacing': ['off'],
    'react/jsx-child-element-spacing': ['off'],
    'react/jsx-closing-bracket-location': ['off'],
    'react/jsx-closing-tag-location': ['off'],
    'react/jsx-curly-newline': ['off'],
    'react/jsx-curly-spacing': ['off'],
    'react/jsx-equals-spacing': ['off'],
    'react/jsx-first-prop-new-line': ['off'],
    'react/jsx-indent': ['off'],
    'react/jsx-indent-props': ['off'],
    'react/jsx-max-props-per-line': ['off'],
    'react/jsx-newline': ['off'],
    'react/jsx-one-expression-per-line': ['off'],
    'react/jsx-props-no-multi-spaces': ['off'],
    'react/jsx-tag-spacing': ['off'],
    'react/jsx-wrap-multilines': ['off'],
    'unicorn/empty-brace-spaces': ['off'],
    'unicorn/no-nested-ternary': ['off'],
    'unicorn/number-literal-case': ['off'],
    'generator-star': ['off'],
    'indent-legacy': ['off'],
    'no-arrow-condition': ['off'],
    'no-comma-dangle': ['off'],
    'no-reserved-keys': ['off'],
    'no-space-before-semi': ['off'],
    'no-spaced-func': ['off'],
    'no-wrap-func': ['off'],
    'space-after-function-name': ['off'],
    'space-after-keywords': ['off'],
    'space-before-function-parentheses': ['off'],
    'space-before-keywords': ['off'],
    'space-in-brackets': ['off'],
    'space-return-throw-case': ['off'],
    'space-unary-word-ops': ['off'],
    'react/jsx-space-before-closing': ['off'],
    'array-callback-return': ['warn'],
    'default-case': [
      'warn',
      {
        commentPattern: '^no default$',
      },
    ],
    eqeqeq: ['warn', 'smart'],
    'no-array-constructor': ['warn'],
    'no-caller': ['warn'],
    'no-cond-assign': ['warn', 'except-parens'],
    'no-const-assign': ['warn'],
    'no-control-regex': ['warn'],
    'no-delete-var': ['warn'],
    'no-dupe-args': ['warn'],
    'no-dupe-class-members': ['warn'],
    'no-dupe-keys': ['warn'],
    'no-duplicate-case': ['warn'],
    'no-empty-character-class': ['warn'],
    'no-empty-pattern': ['warn'],
    'no-eval': ['warn'],
    'no-ex-assign': ['warn'],
    'no-extend-native': ['warn'],
    'no-extra-bind': ['warn'],
    'no-extra-label': ['warn'],
    'no-fallthrough': ['warn'],
    'no-func-assign': ['warn'],
    'no-implied-eval': ['warn'],
    'no-invalid-regexp': ['warn'],
    'no-iterator': ['warn'],
    'no-label-var': ['warn'],
    'no-labels': [
      'warn',
      {
        allowLoop: true,
        allowSwitch: false,
      },
    ],
    'no-lone-blocks': ['warn'],
    'no-loop-func': ['warn'],
    'no-multi-str': ['warn'],
    'no-global-assign': ['warn'],
    'no-unsafe-negation': ['warn'],
    'no-new-func': ['warn'],
    'no-new-object': ['warn'],
    'no-new-symbol': ['warn'],
    'no-new-wrappers': ['warn'],
    'no-obj-calls': ['warn'],
    'no-octal': ['warn'],
    'no-octal-escape': ['warn'],
    'no-redeclare': ['warn'],
    'no-regex-spaces': ['warn'],
    'no-restricted-syntax': ['warn', 'WithStatement'],
    'no-script-url': ['warn'],
    'no-self-assign': ['warn'],
    'no-self-compare': ['warn'],
    'no-sequences': ['warn'],
    'no-shadow-restricted-names': ['warn'],
    'no-sparse-arrays': ['warn'],
    'no-template-curly-in-string': ['warn'],
    'no-this-before-super': ['warn'],
    'no-throw-literal': ['warn'],
    'no-undef': ['error'],
    'no-restricted-globals': [
      'error',
      'addEventListener',
      'blur',
      'close',
      'closed',
      'confirm',
      'defaultStatus',
      'defaultstatus',
      'event',
      'external',
      'find',
      'focus',
      'frameElement',
      'frames',
      'history',
      'innerHeight',
      'innerWidth',
      'length',
      'location',
      'locationbar',
      'menubar',
      'moveBy',
      'moveTo',
      'name',
      'onblur',
      'onerror',
      'onfocus',
      'onload',
      'onresize',
      'onunload',
      'open',
      'opener',
      'opera',
      'outerHeight',
      'outerWidth',
      'pageXOffset',
      'pageYOffset',
      'parent',
      'print',
      'removeEventListener',
      'resizeBy',
      'resizeTo',
      'screen',
      'screenLeft',
      'screenTop',
      'screenX',
      'screenY',
      'scroll',
      'scrollbars',
      'scrollBy',
      'scrollTo',
      'scrollX',
      'scrollY',
      'self',
      'status',
      'statusbar',
      'stop',
      'toolbar',
      'top',
    ],
    'no-unreachable': ['warn'],
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
        enforceForJSX: false,
      },
    ],
    'no-unused-labels': ['warn'],
    'no-unused-vars': [
      'warn',
      {
        args: 'none',
        ignoreRestSiblings: true,
      },
    ],
    'no-use-before-define': [
      'warn',
      {
        functions: false,
        classes: false,
        variables: false,
      },
    ],
    'no-useless-computed-key': ['warn'],
    'no-useless-concat': ['warn'],
    'no-useless-constructor': ['warn'],
    'no-useless-escape': ['warn'],
    'no-useless-rename': [
      'warn',
      {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
      },
    ],
    'no-with': ['warn'],
    'react-hooks/exhaustive-deps': ['warn'],
    'require-yield': ['warn'],
    strict: ['warn', 'never'],
    'use-isnan': ['warn'],
    'valid-typeof': ['warn'],
    'no-restricted-properties': [
      'error',
      {
        object: 'require',
        property: 'ensure',
        message:
          'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
      },
      {
        object: 'System',
        property: 'import',
        message:
          'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
      },
    ],
    'getter-return': ['warn'],
    'import/first': ['error'],
    'import/no-amd': ['error'],
    'import/no-anonymous-default-export': ['warn'],
    'import/no-webpack-loader-syntax': ['error'],
    'react/forbid-foreign-prop-types': [
      'warn',
      {
        allowInPropTypes: true,
      },
    ],
    'react/jsx-no-comment-textnodes': ['warn'],
    'react/jsx-no-duplicate-props': ['warn'],
    'react/jsx-no-target-blank': ['warn'],
    'react/jsx-no-undef': ['error'],
    'react/jsx-pascal-case': [
      'warn',
      {
        allowAllCaps: true,
        ignore: [],
      },
    ],
    'react/no-danger-with-children': ['warn'],
    'react/no-direct-mutation-state': ['warn'],
    'react/no-is-mounted': ['warn'],
    'react/no-typos': ['error'],
    'react/require-render-return': ['error'],
    'react/style-prop-object': ['warn'],
    'jsx-a11y/alt-text': ['warn'],
    'jsx-a11y/anchor-has-content': ['warn'],
    'jsx-a11y/anchor-is-valid': [
      'warn',
      {
        aspects: ['noHref', 'invalidHref'],
      },
    ],
    'jsx-a11y/aria-activedescendant-has-tabindex': ['warn'],
    'jsx-a11y/aria-props': ['warn'],
    'jsx-a11y/aria-proptypes': ['warn'],
    'jsx-a11y/aria-role': [
      'warn',
      {
        ignoreNonDOM: true,
      },
    ],
    'jsx-a11y/aria-unsupported-elements': ['warn'],
    'jsx-a11y/heading-has-content': ['warn'],
    'jsx-a11y/iframe-has-title': ['warn'],
    'jsx-a11y/img-redundant-alt': ['warn'],
    'jsx-a11y/no-access-key': ['warn'],
    'jsx-a11y/no-distracting-elements': ['warn'],
    'jsx-a11y/no-redundant-roles': ['warn'],
    'jsx-a11y/role-has-required-aria-props': ['warn'],
    'jsx-a11y/role-supports-aria-props': ['warn'],
    'jsx-a11y/scope': ['warn'],
    'react-hooks/rules-of-hooks': ['error'],
    'react/jsx-uses-vars': ['warn'],
    'react/jsx-uses-react': ['warn'],
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
  ignorePatterns: [],
};
